import { Montserrat, Playfair_Display, Dancing_Script } from "next/font/google";
import "./globals.css";

const playfairDisplay = Playfair_Display({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});
const dancingScript = Dancing_Script({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});
const montserrat = Montserrat({
   variable: "--font-geist-mono",
   subsets: ["latin"],
});

export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body
            className={`${playfairDisplay.variable} ${dancingScript.variable} ${montserrat.variable} antialiased`}
         >
            {children}
         </body>
      </html>
   );
}
